### ISSUE TITLE
crash on startup using multiplayer

### ISSUE THREAD

**Issue by LordDecay26** [jusipat/CastleBlocks#13]
i am on fabric 0.14.9 for Minecraft 1.18.2, my modpack is thus: https://www.curseforge.com/minecraft/modpacks/besmirchment-psm
all client-side mods have been removed from the mod files in the multiplayer server.

the log says this
https://pastebin.com/BWiccXG5

**Comment by jusipat** [comment]
I will look at this as soon as I can!

**Comment by jusipat** [comment]
A new build has been released [here](https://www.curseforge.com/minecraft/mc-mods/castleblocks/files/3951755).
Please reopen this if this does not resolve the issue, thanks,
