### ISSUE TITLE
Trowel nonexistent?

### ISSUE THREAD

**Issue by Mdbgamer** [jusipat/CastleBlocks#18]
As of the 1.19.2 Forge version, absolutely nothing from the mod shows up in JEI or the creative menu. I'm not sure what's going on there. >.>

**Comment by Mdbgamer** [comment]
Everything still works. You can craft the trowels, the blocks still do their thing, but like... nothing shows up in the creative or JEI menus.

**Comment by jusipat** [comment]
Hi, this is a known issue, due to the changes to itemgroups and the creative menu in 1.19.2. This was fixed in future versions of the mod but was never backported
