### ISSUE TITLE
No Config or Config is Empty

### ISSUE THREAD

**Issue by JasdanVM** [jusipat/CastleBlocks#23]
In my server, Castle Blocks didn't generate any config file
In my client side, it did, but, this is all it has:

`{}`

That's it, please help me know what things can even be configured in the first place.
The version is castleblocks-1.20.x-1.3.0 for Fabric 1.20.1

**Comment by JasdanVM** [comment]
I saw there was Mod Menu integration
But the changes there don't stick
I tried to edit it manually based on the GitHub repository
![notepad++_oOEjQpFf9i](https://github.com
/jusipat/CastleBlocks/assets/109768767/9eea1bf0-1352-4aea-8923-a6fb6a8fb9a0)
But when I launch the game, it got overriden
![notepad++_nB8ayLlwpH](https://github.com/jusipat/CastleBlocks/assets/109768767/447d5ecb-ac3c-4778-a787-6cf041b1944d)
I can't do anything?

**Comment by JasdanVM** [comment]
I saw there was Mod Menu integration
But the changes there don't stick
I tried to edit it manually based on the GitHub repository


But when I launch the game, it got overriden

**Comment by JasdanVM** [comment]
I tried to use this settings:
![notepad++_oOEjQpFf9i](https://github.com/jusipat/CastleBlocks/assets/109768767/f4d168a3-7d10-4709-a8e5-b0334ce9fb6e)

But they get deleted and replaced for this:
![image](https://github.com/jusipat/CastleBlocks/assets/109768767/1496cf8d-5323-496f-993e-d5bde5e281fc)

**Comment by jusipat** [comment]
It seems like the latest version on Fabric has issues with user configs, I will work on a fix!

**Comment by JasdanVM** [comment]
Thanks for responding, the other issues I had were a result of not finding a config file in the server.
Any potential timeframe for the fix just so I know when to check for it?

**Comment by jusipat** [comment]
1.3.1 for Fabric 1,20.1 & 1.20.4 have been released, fixing it!
