### ISSUE TITLE
Add integrated Blacklist for the mod "Carryon"

### ISSUE THREAD

**Issue by JasdanVM** [jusipat/CastleBlocks#24]
It's easy for someone to install the two without realizing that you can pick up CastleBlocks without being the owner.

This also leads me to ask, are the Castle Blocks "block entities"?
So, would it hurt performance to have lots of them?

**Comment by jusipat** [comment]
CarryOn has its own blacklist configuration files which you can add CastleBlocks to. I fail to see the relevance of this issue.
Castle blocks are block entities which store the NBT data of their owner. The potential effect on game performance is nil.
