### ISSUE TITLE
config option in 1.16.5 backport

### ISSUE THREAD

**Issue by ByPaco10** [jusipat/CastleBlocks#26]
Sorry, but the a config option was not included in this backport. Best that could be done for now is using the different Trowel varieties for different durability. The same goes for changing the castle block types.

_Originally posted by @jusipat in https://github.com/jusipat/CastleBlocks/issues/11#issuecomment-1180897771_

If it is possible, could you update the backport to include config files? Config files for this mod are extremely important and having a 1.16.5 version without them makes this mod unusable for more complex modpacks

**Comment by jusipat** [comment]
> Sorry, but the a config option was not included in this backport. Best that could be done for now is using the different Trowel varieties for different durability. The same goes for changing the castle block types.
> 
> _Originally posted by @jusipat in [#11 (comment)](https://github.com/jusipat/CastleBlocks/issues/11#issuecomment-1180897771)_
> 
> If it is possible, could you update the backport to include config files? Config files for this mod are extremely important and having a 1.16.5 version without them makes this mod unusable for more complex modpacks

The config only handles the Castleblock's resistance, hardness, and PvP enabling features. The proposed trowel configurability has never been implemented. Unfortunately with how old 1.16.5 now is, I have no plans to backport any new content, including configs.
