### ISSUE TITLE
Eroor where the castle door does not open

### ISSUE THREAD

**Issue by MIN021010** [jusipat/CastleBlocks#27]
they said "key could not be linked, set key limit exceeded!"

**Comment by jusipat** [comment]
Hi, please provide more details regarding what lead to this error, and make sure you have read instructions on Castle Doors, in case you haven't: https://github.com/jusipat/CastleBlocks/wiki/Castle-Doors

**Comment by MIN021010** [comment]
I connected redstone to the castle door in creative mode, but it didn't open. I also tried using the key."

**Comment by jusipat** [comment]
> they said "key could not be linked, set key limit exceeded!"

This means you have used too many keys, assuming you have paired the maximum number of keys and lost them, you have to get a new door. Just to be sure please provide what version you are on so I can test this
